#!/usr/bin/env bash
# Configure another webserver

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

hostname=$(hostname)

echo "add_header X-Served-By $hostname;" | sudo tee /etc/nginx/sites-available/default/
sudo service nginx restart
