#!/usr/bin/env bash
# configure web server and add Nginx header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
printf "server {
    listen 80;
    listen [::]:80 default_server;
    add_header X-Served-By \$hostname;
    root /usr/share/nginx/html;
    index index.html index.htm;
    location /redirect_me {
         return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html {
          root /usr/share/nginx/html;
          internal;
    }
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart

