#!/usr/bin/env bash
#  Bash script that configures an Ubuntu server.

cp /etc/hosts ~/etc/hosts.bak
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/etc/hosts.bak
cp -f ~/etc/hosts.bak /etc/hosts
